'use client';
import { useEffect, useMemo, useState } from 'react';
import { makeSampleSources } from '@/data/sampleSources';
import type { PipelineResult, Project, Source } from '@/lib/types';
const uid=(p:string)=>`${p}_${Math.random().toString(36).slice(2,9)}`;
export default function Home(){
 const [configured,setConfigured]=useState(false),[setup,setSetup]=useState('Checking LLM setup...'),[project,setProject]=useState<Project>({id:uid('proj'),name:'Backend onboarding sprint',audience:'Backend Engineering Intern',goal:'Ramp up to making a first PR',createdAt:new Date().toISOString()}),[sources,setSources]=useState<Source[]>([]),[text,setText]=useState(''),[title,setTitle]=useState('Pasted wiki notes'),[result,setResult]=useState<PipelineResult|null>(null),[err,setErr]=useState(''),[loading,setLoading]=useState(false),[done,setDone]=useState<Record<string,boolean>>({});
 useEffect(()=>{fetch('/api/generate').then(r=>r.json()).then(d=>{setConfigured(d.configured);setSetup(d.message)})},[]);
 const lessons=useMemo(()=>result?.course.modules.flatMap(m=>m.lessons)||[],[result]); const complete=lessons.filter(l=>done[l.id]).length;
 function addSource(raw=text,name=title,type:'paste'|'txt'|'md'='paste'){ if(!raw.trim())return; setSources(s=>[...s,{id:uid('src'),projectId:project.id,title:name,type,rawText:raw,createdAt:new Date().toISOString()}]); setText(''); }
 async function files(fs:FileList|null){ if(!fs)return; for(const f of Array.from(fs)){ if(!/\.(txt|md)$/i.test(f.name)) continue; addSource(await f.text(),f.name,f.name.endsWith('.md')?'md':'txt'); } }
 async function generate(){setLoading(true);setErr('');setResult(null);try{const r=await fetch('/api/generate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({project,sources})});const d=await r.json();if(!r.ok)throw new Error(d.error);setResult(d)}catch(e){setErr((e as Error).message)}finally{setLoading(false)}}
 function editLesson(id:string,field:'explanation'|'example',value:string){setResult(r=>r&&({...r,course:{...r.course,modules:r.course.modules.map(m=>({...m,lessons:m.lessons.map(l=>l.id===id?{...l,[field]:value}:l)}))}}))}
 function publish(){setResult(r=>r&&({...r,course:{...r.course,published:true}}))}
 return <main><section className="hero"><div><span className="tag">Grounded AI onboarding</span><h1>From messy docs to new-hire ramp plans</h1><p className="muted">RampForge turns vetted internal material into role-specific modules, lessons, quizzes, tasks, and citations. No API key means no generated content.</p><div className="flow"><span className="pill active">messy sources</span><span className="pill active">objectives</span><span className="pill active">course</span><span className="pill">review</span><span className="pill">learn</span></div></div><div className="card"><h2>LLM setup</h2><p>{setup}</p>{!configured&&<div className="warn">Generation is unavailable until OPENAI_API_KEY is configured. Use OPENAI_BASE_URL for IBM Bob/open-source OpenAI-compatible APIs.</div>}</div></section>
 <section className="grid" style={{marginTop:18}}><div className="card"><h2>1. Project</h2><label>Project name<input value={project.name} onChange={e=>setProject({...project,name:e.target.value})}/></label><label>Role / audience<input value={project.audience} onChange={e=>setProject({...project,audience:e.target.value})}/></label><label>Goal<input value={project.goal||''} onChange={e=>setProject({...project,goal:e.target.value})}/></label></div><div className="card"><h2>2. Add sources</h2><label>Title<input value={title} onChange={e=>setTitle(e.target.value)}/></label><textarea placeholder="Paste README, wiki notes, transcript, setup guide..." value={text} onChange={e=>setText(e.target.value)}/><button onClick={()=>addSource()}>Add pasted source</button><p><input type="file" multiple accept=".txt,.md" onChange={e=>files(e.target.files)}/></p><button className="ghost" onClick={()=>setSources(makeSampleSources(project.id))}>Load sample source materials</button></div><div className="card"><h2>3. Generate</h2><p className="muted">Runs chunking, objective extraction, dedupe, outline, and grounded lesson generation through a real LLM call.</p><button disabled={!configured||!sources.length||loading} onClick={generate}>{loading?'Generating with LLM...':'Generate grounded course'}</button>{err&&<div className="warn">{err}</div>}</div></section>
 <section className="two" style={{marginTop:18}}><div className="card"><h2>Source vault</h2>{sources.map(s=><div className="source" key={s.id}><b>{s.title}</b><p className="muted">{s.type} · {s.rawText.length} chars · vetted source input</p><details><summary>Preview</summary><pre style={{whiteSpace:'pre-wrap'}}>{s.rawText.slice(0,900)}</pre></details></div>)}</div><div className="card"><h2>Transformation artifacts</h2>{result?<><p><b>{result.chunks.length}</b> chunks with citation labels</p><p><b>{result.objectives.length}</b> deduped objectives extracted by LLM</p>{result.objectives.map(o=><div className="citation" key={o.id}>{o.title} · {o.type} · difficulty {o.difficulty}<br/>Evidence: {o.evidenceChunkIds.join(', ')}</div>)}</>:<p className="muted">Artifacts appear here after real generation.</p>}</div></section>
 {result&&<section className="kanban" style={{marginTop:18}}><div className="card"><h2>Manager review</h2>{result.warnings.length>0&&<div className="warn">Weak support warnings: {result.warnings.join('; ')}</div>}<button className="secondary" onClick={publish}>{result.course.published?'Published':'Approve / publish'}</button>{result.course.modules.map(m=><div key={m.id} className="source"><h3>{m.title}</h3><p>{m.description}</p>{m.lessons.map(l=><div key={l.id} className="lesson"><b>{l.title}</b><p className="muted">Support: {l.supportLevel}</p><label>Lesson text<textarea value={l.explanation} onChange={e=>editLesson(l.id,'explanation',e.target.value)}/></label><label>Example<textarea value={l.example} onChange={e=>editLesson(l.id,'example',e.target.value)}/></label>{l.citations.map(c=><div className="citation" key={c.chunkId}>{c.chunkId}: {c.sourceTitle} — {c.locationLabel}</div>)}</div>)}</div>)}</div><div className="card"><h2>Learner course</h2><h3>{result.course.title}</h3><p className="muted">For {result.course.audience}</p><div className="progress"><span style={{width:`${lessons.length?complete/lessons.length*100:0}%`}}/></div><p>{complete}/{lessons.length} lessons complete</p>{result.course.modules.map(m=><div key={m.id} className="source"><h3>{m.title}</h3>{m.lessons.map(l=><div key={l.id} className="lesson"><label><input style={{width:'auto'}} type="checkbox" checked={!!done[l.id]} onChange={e=>setDone({...done,[l.id]:e.target.checked})}/> {l.title}</label><p>{l.explanation}</p><b>Key terms:</b> {l.keyTerms.join(', ')}<p><b>Checkpoint:</b> {l.quiz[0]?.question}</p>{l.task&&<p><b>Task:</b> {l.task.title} — {l.task.instructions}</p>}<details><summary>Source citations</summary>{l.citations.map(c=><div className="citation" key={c.chunkId}>{c.locationLabel}<br/>{c.quote}</div>)}</details></div>)}</div>)}</div></section>}
 </main>}
